name: ExamplePluginDCommandLib
version: '${project.version}'
main: me.dlands.dcommand.exampleplugin.Main
api-version: 1.16
commands:
  testcommand:
    usage: /  testcommand help
    description: "Testcommand doang ini"
depend:
  - DCommandLib
